### PR TITLE
adapting grass* functions

### PR DESCRIPTION
**Pull request by bniebuhr**
Hi,

In the updated NINA server we have two new issues:
- new GIS server name
- grass8 instead of grass7 - so we need to use the package `rgrass` now, instead of `rgrass7`

I made the changes in the relevant functions.

### CODE REVIEW

**Comment by bniebuhr** [comment]
@jenast can you take a fast look?

I only tested grassConnect and it is working here now.

**Review by jenast — APPROVED** [review]

**Comment by jenast** [comment]
There's something I don't understand here. I can't seem to approve the pull request.

**Comment by bniebuhr** [comment]
Yes, I don't know either. Since you reviewed and approved the changes, it should work... Maybe @frafra can help us, if he knows more about the technicalities of the process?

**Comment by frafra** [comment]
Hi everybody. I recently removed some users from being administrators of the whole NINAnor group. This triggered an issue in NinaR, since the group of users for this group did not have write permissions for some reason (it has been probably set incorrectly in the past). I removed non-NINA users and gave write permission to the NinaR group of users (which is composed only by Jens).

**Comment by frafra** [comment]
I accepted the PR for you, but Jens now has the right to do that, without needing admin powers at the organization level.

Happy coding! :)

**Pull request merged**
